### ISSUE TITLE
Supabase Auth JWT Key

### ISSUE THREAD

**Issue by andrezimpel** [electric-sql/electric#1074]
I don't really know where to put this, but I've been following the instructions for Supabase and how to use auth with electric sql. I was running in an issue very single time where `await electric.connect(session?.access_token)` ended up in AUTH_REQUIRED. 

I figured out that I have to base 64 encode the Supabase JWT secret in order for auth to really work.

**Comment by msfstef** [comment]
Assuming the access token is present in the above statement you should not need to further encode the JWT as it already is base64 encoded, it should work out of the box as returned from Supabase.

Could you provide a more complete example of the issue you are running into?

**Comment by andrezimpel** [comment]
@msfstef it's basically just as described. If I use the jwt secret from sup abase as it is every time the client wants to connect the server returns an error with "AUTH_REQUIRED". When I base64 encode the supabase jwt (AUTH_JWT_KEY) and redeploy the server (fly.io) it starts working.

**Comment by AntonOfTheWoods** [comment]
@andrezimpel , I can't find it but this is/was a known issue (which I can't find unfortunately). Apparently it tries to decode and if that doesn't fail then it assumes the incoming key is in base64, rather than not. It was an example of trying to be overly helpful I guess. It was supposed to be on someone's TODOs so it may be fixed in the latest version?

**Comment by andrezimpel** [comment]
@AntonOfTheWoods I still have the issue with 0.10.  Maybe it makes sense to add a note to the docs in this case.

**Comment by alco** [comment]
@andrezimpel Thanks for raising this issue! We'll work on including a fix for this problem in the upcoming release.

**Comment by federico-hv** [comment]
I'm having a similar issue. I am running electric using a docker compose file and it seems to be connecting with my supabase db well since I'm able to run the migrations using the npm script. However from the client side in my react application (where I'm using the supabase client), even though the `supabase.auth.signInWithPassword` method retrieves the token, this token is not working with the `await electric.connect(session?.access_token)` section as @andrezimpel mentioned and I'm getting the same error while debugging:

##### Client logs of electric with `config.debug` true

```
[proto] recv: #SatRpcResponse{method: authenticate, requestId: 2, error: #SatErrorResp{type: AUTH_REQUIRED}}

{
  $type: "Electric.Satellite.SatErrorResp"
  errorType: 1
  lsn: undefined
  message: undefined
}
```


##### Server side

`[warning] Client authentication failed: Signing algorithm mismatch`



The server side says there's an algorith mismatch but I'm using `HS256` as suggested in the docs for the environment variable. I analyzed the token in [jwt.io](https://jwt.io/) and it says I'm authenticated and contains the claims `sub`, `iat`, `exp`, `iss` and `aud`. The client retrieves data from supabase correctly when making queries.





Some more info....


##### npm script works well

```
"db:migrate": "npx electric-sql with-config \"npx pg-migrations apply --database {{ELECTRIC_PROXY}} --directory ./db/migrations\""
```


##### Docker compose file

```
version: "3.7"
services:
  electric:
    image: electricsql/electric:0.9
    ports:
      - "5133:5133"
      - "5132:5132"
      - "65432:65432"
    environment:
      - AUTH_JWT_ALG=HS256
      - AUTH_JWT_KEY=<mySupabaseKey>
      - DATABASE_URL=.<mySupabaseDbUrl>
      - ELECTRIC_WRITE_TO_PG_MODE=direct_writes
      - PG_PROXY_PASSWORD=<myProxyPassword>
      - PG_PROXY_PORT=65432

    networks:
      - ip6net

networks:
  ip6net:
    external: true
```
