### ISSUE TITLE
Electric doesn't clean shapes after connecting to a new postgres with a different schema

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#1689]
steps to reproduce:
1. Follow the quickstart and add the table `foo` with a few rows of data
2. Fetch the foo table shape
3. Restart Postgres as an empty db
4. Electric reconnects
5. Try fetching the foo shape and see that the old data is returned instead of the table not found error

[DIscord link](https://discord.com/channels/933657521581858818/1284172917059616970/1284177755935739925)

**Comment by KyleAMathews** [comment]
lirbank (discord user name) also tried inserting new rows into the new database (with identical table) and those weren't added to the shape. So perhaps we're also missing adding the right publication when we connect to the new db? cc @kevin-dp

**Comment by lirbank** [comment]
@lirbank on GH too 😃

**Comment by thruflo** [comment]
I've slightly addressed this here https://electric-sql.com/docs/guides/troubleshooting#clear-data-mdash-how-do-i-clear-the-server-state -- I wonder (a) if we want to add some functionality to wipe shapes when PG changes or (b) whether we want to be clearer about the behaviour and if so where and how to document.

One thing we've done before for telemetry is write a unique identifier into the PG instance. Perhaps one approach here could be when Electric starts it can get-or-create a uuid and then use it internally as part of the shape lookup.

**Comment by lirbank** [comment]
I just did this:

1. Fired up the quickstart docker compose file
2. Created todo table, added 200,000 rows
3. Run the curl command, shows the 200,000 rows ✅
4. Dropped the todo table
5. Run the curl command, shows the 200,000 rows ❌
6. Create the todo table again, added 200,000 rows again but with different "task" names so it is clearly different from the original data set
5. Run the curl command, still shows the original 200,000 rows ❌

**Comment by KyleAMathews** [comment]
ok so very broken 😬

**Comment by lirbank** [comment]
Here is another:

1. Remove all docker containers and start fresh
2. Create the todo table
3. Insert some rows
4. Run `DELETE FROM todo;`
5. Now `curl -i 'http://localhost:3000/v1/shape/todo?offset=-1` still return the stale data
6. `SELECT COUNT(*) FROM todo;` return 0

Docker image is now canary:

`electricsql/electric:canary`
`sha256:5d0db221daf0f74d6dd2bbba034612d626e15905f3a784273b8e27c75c5e81cd`

**Comment by lirbank** [comment]
FYI I have modified the docker-compose.yaml, not using tmpfs for postgres data coz it run out of storage.

```
version: "3.3"
name: "electric_quickstart"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: electric
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 54321:5432
    tmpfs:
      # - /var/lib/postgresql/data
      - /tmp
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical

  electric:
    image: electricsql/electric:canary
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/electric
    ports:
      - "3000:3000"
    depends_on:
      - postgres
```
