### ISSUE TITLE
(FunctionClauseError) no function clause matching in Electric.Replication.ShapeLogCollector.handle_call

### ISSUE THREAD

**Issue by emakarov** [electric-sql/electric#1870]
Experiencing these logs on the simplest setup via docker compose
What can be the issue?

    ** (EXIT) time out
    (elixir 1.17.2) lib/gen_server.ex:1128: GenServer.call/3
    (opentelemetry 1.4.0) /app/deps/opentelemetry/src/otel_tracer_default.erl:47: :otel_tracer_default.with_span/5
    (electric 0.7.6) lib/electric/telemetry/open_telemetry.ex:67: anonymous fn/3 in Electric.Telemetry.OpenTelemetry.with_span/3
    (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (electric 0.7.6) lib/electric/postgres/replication_client.ex:222: Electric.Postgres.ReplicationClient.process_x_log_data/3
    (opentelemetry 1.4.0) /app/deps/opentelemetry/src/otel_tracer_default.erl:47: :otel_tracer_default.with_span/5
    (electric 0.7.6) lib/electric/telemetry/open_telemetry.ex:67: anonymous fn/3 in Electric.Telemetry.OpenTelemetry.with_span/3
    (telemetry 1.2.1) /app/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (postgrex 0.19.0) lib/postgrex/replication_connection.ex:551: Postgrex.ReplicationConnection.handle/5
    (postgrex 0.19.0) lib/postgrex/replication_connection.ex:537: Postgrex.ReplicationConnection.handle_data/2
    (stdlib 6.0.1) gen_statem.erl:3115: :gen_statem.loop_state_callback/11
    (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
Queue: [info: {:tcp, #Port<0.346>, <<100, 0, 0, 10, 188, 119, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 199, 189, 8, 160, 126, 1, 82, 0, 0, 84, 67, 112, 117, 98, 108, 105, 99, 0, 115, 105, 109, 117, ...>>}]
Postponed: []

11:04:26.165 [info] Postgres server version = 140013, system identifier = 7402080357957849128, timeline_id = 1

11:04:26.197 [info] Starting replication from postgres

11:04:26.268 [error] GenServer {Electric.Registry.Processes, {Electric.Replication.ShapeLogCollector, :default}} terminating
** (FunctionClauseError) no function clause matching in Electric.Replication.ShapeLogCollector.handle_call/3

**Comment by alco** [comment]
Hey @emakarov. Can you show the remaining log? There's normally also a stacktrace.

I would venture a guess that your Docker setup doesn't use persistent volume which would result in the shape logs to be lost upon container restart.

Could you share your compose file to help us investigate? Also, which version of the sync service are you running?

**Comment by emakarov** [comment]
extract of the docker compose looks like this, so I just copied from tutorial the sync

```
version: "3"

networks:
  backend:
    internal: true

  internet:

volumes:
  pgdata_volume:

services:
  db:
    image: postgis/postgis:14-3.4
    container_name: pg-db
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_DB=pgdb
      - POSTGRES_PASSWORD=pgpassword
      - PGDATA=/var/lib/postgresql/data
    command: "postgres -c log_statement=all -c listen_addresses=* -c wal_level=logical"
    restart: always

    networks:
      - backend
      - internet

    volumes:
      - pgdata_volume:/var/lib/postgresql/data

    tmpfs:
      - /tmp

    ports:
      - "5432:5432/tcp"

  electric:
    image: electricsql/electric
    container_name: electric
    environment:
      DATABASE_URL: postgresql://pguser:pgpassword@pg-db:5432/pgdb?sslmode=disable
    ports:
      - "3001:3000"
    depends_on:
      - db

    networks:
      - backend
      - internet
  ```
  
  stacktrace
  ```
  13:22:09.753 [error] GenServer {Electric.Registry.Processes, {Electric.Replication.ShapeLogCollector, :default}} terminating
** (FunctionClauseError) no function clause matching in Electric.Replication.ShapeLogCollector.handle_call/3
    (electric 0.7.6) lib/electric/replication/shape_log_collector.ex:118: Electric.Replication.ShapeLogCollector.handle_call({:relation_msg, %Electric.Replication.Changes.Relation{id: 21571, schema: "public", table: "simulation_simulation", columns: [%Electric.Replication.Changes.Column{name: "id", type_oid: 23}, %Electric.Replication.Changes.Column{name: "created_at", type_oid: 1184}, %Electric.Replication.Changes.Column{name: "completed_at", type_oid: 1184}, %Electric.Replication.Changes.Column{name: "name", type_oid: 1043}, %Electric.Replication.Changes.Column{name: "state", type_oid: 1043}, %Electric.Replication.Changes.Column{name: "mixed_fleet", type_oid: 16}, %Electric.Replication.Changes.Column{name: "geofence_id", type_oid: 2950}, %Electric.Replication.Changes.Column{name: "start_time", type_oid: 1184}, %Electric.Replication.Changes.Column{name: "end_time", type_oid: 1184}, %Electric.Replication.Changes.Column{name: "conversion_rate", type_oid: 701}, %Electric.Replication.Changes.Column{name: "journey_duration_source", type_oid: 1043}, %Electric.Replication.Changes.Column{name: "number_of_vehicles", type_oid: 23}, %Electric.Replication.Changes.Column{name: "road_network", type_oid: 1043}, %Electric.Replication.Changes.Column{name: "vehicle_capacity", type_oid: 23}, %Electric.Replication.Changes.Column{name: "min_advance_booking_window", type_oid: 23}, %Electric.Replication.Changes.Column{name: "max_advance_booking_window", type_oid: 23}, %Electric.Replication.Changes.Column{name: "acceptable_waiting_time", type_oid: 23}, %Electric.Replication.Changes.Column{name: "max_additional_journey_time", type_oid: 23}, %Electric.Replication.Changes.Column{name: "odbs_trip_duration", type_oid: 23}, %Electric.Replication.Changes.Column{name: "driver_prep_time", type_oid: 23}, %Electric.Replication.Changes.Column{name: "min_driver_rest_time", type_oid: 23}, %Electric.Replication.Changes.Column{name: "percentage_driver_rest_time", type_oid: 701}, %Electric.Replication.Changes.Column{name: "used_vehicles_count", type_oid: 23}, %Electric.Replication.Changes.Column{name: "in_service_mileage", type_oid: 23}, %Electric.Replication.Changes.Column{name: "dead_mileage", type_oid: 23}, %Electric.Replication.Changes.Column{name: "transfer_rate", type_oid: 701}, %Electric.Replication.Changes.Column{name: "bookings_count", type_oid: 23}, %Electric.Replication.Changes.Column{name: "completed_odbs_trips_count", type_oid: 23}, %Electric.Replication.Changes.Column{name: "completed_fixed_route_trips_count", type_oid: 23}, %Electric.Replication.Changes.Column{name: "no_offer_count", type_oid: 23}, %Electric.Replication.Changes.Column{name: "odbs_trips_per_vehicle_per_hour", type_oid: 701}, %Electric.Replication.Changes.Column{name: "avg_waiting_time", type_oid: 701}, %Electric.Replication.Changes.Column{name: "min_waiting_time", type_oid: 701}, %Electric.Replication.Changes.Column{name: "max_waiting_time", type_oid: 701}, %Electric.Replication.Changes.Column{name: "avg_planned_actual_journey_time_difference", type_oid: 701}, %Electric.Replication.Changes.Column{name: "min_planned_actual_journey_time_difference", type_oid: 701}, %Electric.Replication.Changes.Column{name: "max_planned_actual_journey_time_difference", type_oid: 701}, %Electric.Replication.Changes.Column{name: "avg_waiting_time_difference", type_oid: 701}, %Electric.Replication.Changes.Column{name: "min_waiting_time_difference", type_oid: 701}, %Electric.Replication.Changes.Column{name: "max_waiting_time_difference", type_oid: 701}, %Electric.Replication.Changes.Column{name: "avg_journey_time_difference", type_oid: 701}, %Electric.Replication.Changes.Column{name: "min_journey_time_difference", type_oid: 701}, %Electric.Replication.Changes.Column{name: "max_journey_time_difference", ...}, %Electric.Replication.Changes.Column{...}, ...]}}, {#PID<0.2893.0>, [:alias | #Reference<0.0.370307.1878049856.980484099.221096>]}, %{producer: {#PID<0.2892.0>, [:alias | #Reference<0.0.370179.1878049856.980484099.220824>]}, demand: :accumulate, subscriptions: {0, MapSet.new([])}, electric_instance_id: :default, inspector: {Electric.Postgres.Inspector.EtsInspector, [server: Electric.Postgres.Inspector.EtsInspector]}, link_consumers: true})
    (gen_stage 1.2.1) lib/gen_stage.ex:1942: GenStage.handle_call/3
    (stdlib 6.0.1) gen_server.erl:2209: :gen_server.try_handle_call/4
    (stdlib 6.0.1) gen_server.erl:2238: :gen_server.handle_msg/6
    (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
```
