### ISSUE TITLE
Evaluate docs for GCP

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#2424]
https://electric-sql.com/docs/integrations/gcp

A [user on Discord tried following them](https://discord.com/channels/933657521581858818/933657523049885698/1347264088350265435) and create a new Electric user but it apparently didn't have permission to modify the replication.

`Failed to configure publication, retrying: %Postgrex.Error{message: nil, postgres: %{code: :insufficient_privilege, line: "3583", message: "must be owner of table sometable", file: "aclchk.c", unknown: "ERROR", severity: "ERROR", pg_code: "42501", routine: "aclcheck_error"}, connection_id: 36, query: nil}`

**Comment by yvesnrb** [comment]
(discord user here) some steps to reproduce the problem:

1. Given this Docker Compose configuration:
```yaml
services:
  db:
    image: "postgres:14.7"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    volumes:
      - vol_db:/var/lib/postgresql/data
    networks:
      - mynet
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical      

  electric:
    image: "electricsql/electric"
    environment:
      DATABASE_URL: postgresql://electric:secret@db:5432/mydb?sslmode=disable
    ports:
      - "3131:3000"
    networks:
      - mynet
    depends_on:
      - db

networks:
  showup:
    name: mynet
    driver: bridge

volumes:
  vol_db:
    driver: local
```

2. Connect to the database using the `postgres` user and `secret` password and create a table:
```sql
CREATE TABLE films (
    code        char(5),
    title       varchar(40),
    did         integer,
    date_prod   date,
    kind        varchar(10),
    len         interval hour to minute,
    CONSTRAINT production UNIQUE(date_prod)
);
```

3. Also create the `electric` user as per the GCP instructions:
```sql
CREATE ROLE electric WITH REPLICATION LOGIN PASSWORD 'secret';
GRANT ALL PRIVILEGES ON DATABASE "postgres" to electric;
```

The Electric container initializes cleanly and healthcheck is ok, the problem is when a client attempts to sync a shape.
