### ISSUE TITLE
Rename api_secret param to just secret

### ISSUE THREAD

**Issue by KyleAMathews** [electric-sql/electric#2475]
Also update cloud to just secret.

We'll make this backwards compatible as it's easy to support both params.

**Comment by kevin-dp** [comment]
I opened a PR for renaming the `api_secret` query param to `secret`.
@KyleAMathews what do you mean with:
> Also update cloud to just secret.

I don't think our cloud is using this secret since we are not publicly exposing our cloud Electrics.

**Comment by KyleAMathews** [comment]
We use `source_secret` in cloud as the parameter — so the idea is to also change that to just `secret`.

**Comment by thruflo** [comment]
Actually @kevin-dp I see it the other way. They are the same thing. You always provide a secret when running in secure mode and with the cloud you just also provide a `source_id`. Yes they need to match and may be used differently our-side but from a user's perspective in the proxy, they always add the `secret` param whether it's self-host or cloud.

(As per recent Discord thread we should sort all this out and make sure the docs are accurate and clear).

**Comment by kevin-dp** [comment]
Indeed they both serve as a secret but they protect different things, one protects the entire (self-hosted) Electric API, the other one protects a single instance and is different per instance! I'm afraid that using the same name for both makes it extra hard to document. For instance, a user looking at the OpenAPI spec will see the `secret` parameter which says that this corresponds to the `ELECTRIC_SECRET` set when starting Electric. But should not be confused with the `secret` parameter in cloud Electric, which is the source's secret. If phrased like that perhaps it clears out confusion, not sure.

**Comment by thruflo** [comment]
My argument is that it should be "confused" with the `secret` parameter in cloud Electric. They are both the secret that needs to be provided to authenticate. In the cloud case, you also provide a `source_id` and the secret is validated together with it. In the OS case, the secret is validated on its own.

I think this is a feature, not a bug.

**Comment by kevin-dp** [comment]
@thruflo https://github.com/electric-sql/stratovolt/pull/456

**Comment by burakakca** [comment]
i have this docker compose yaml and i get error how can i fix that? i'm i missing? i'm using db as supabase

```bash
REPOSITORY                              TAG                IMAGE ID       CREATED        SIZE
electricsql/electric                    latest             2c3e1f2b8aa2   3 days ago     166MB
```

```yaml
version: "3.3"
name: "electricsql_quickstart"

services:
  electric:
    image: electricsql/electric
    environment:
      # Updated DATABASE_URL to point to your Supabase Postgres instance.
      # Replaced 127.0.0.1 with host.docker.internal to connect from container to host.
      # Using Supabase default user/pass: postgres/postgres and port 54322, database 'postgres'.
      DATABASE_URL: postgresql://postgres:postgres@host.docker.internal:54322/postgres?sslmode=disable

      # WARNING: Not suitable for production. Only use insecure mode in development
      # or if you've otherwise secured the Electric API.
      # See https://electric-sql.com/docs/guides/security
      # ELECTRIC_INSECURE: true
      ELECTRIC_SECRET: super-secret-jwt-token-with-at-least-32-characters-long
    ports:
      # Exposes the ElectricSQL sync service port
      - "3000:3000"
    restart: always
    # No 'depends_on' needed as Supabase is external and assumed to be running.
    # Make sure your Supabase instance (especially Postgres on port 54322)
    # is running and accessible from your Docker environment BEFORE starting this service.

```


```bash
➜  sync-vocabulary git:(main) ✗ curl -X GET 'http://localhost:3000/v1/shape?table=foo&offset=-1' \
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU0MzIxL2F1dGgvdjEiLCJzdWIiOiI5ZTZjNTg1NS1mMmE5LTRkNDctODEyZS0zNDcyNWYzNWI0ZTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzQ1MTY1ODE0LCJpYXQiOjE3NDUxNjIyMTQsImVtYWlsIjoidGVzdEB0ZXN0LmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzQ1MTYyMjE0fV0sInNlc3Npb25faWQiOiI1MzQ5YjgzYi0zN2RmLTQyZDgtOWRmNS03MzBiYmY4MTY3NTciLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.8APc1MzOPsEqvcZxARgBFLA0bgq9eKw0E_chDp1uqys"

{"message":"Unauthorized - Invalid API secret"}%
```
