### ISSUE TITLE
Windows Compatibility Issue with 'npx electric-sql generate' script

### ISSUE THREAD

**Issue by SamuelC54** [electric-sql/electric#535]
Hello! I've run into a little snag while trying the quick start with the `npx electric-sql generate` script and it seems like it might not be entirely Windows-friendly.

```
12 |   provider = "sqlite"
13 |   url = "file:C:\civalgo\electric-test\.electric_migrations_tmp_KUMjZt\electric.db"
   |
error: Unknown escape sequence. If the value is a windows-style path, `\` must be escaped as `\\`.
  -->  schema.prisma:13
```

the generator generate backslashes that my window machine doesnt like: (it could have generated double backslashes of forward slash) instead to fix this I think

![image](https://github.com/electric-sql/electric/assets/9410224/6fe47792-b347-4568-b384-15beae29753a)

**Comment by balegas** [comment]
We've set up things to work with Windows, but we haven't actually tested. Opening an internal issue to address it.

**Comment by ulricden** [comment]
to test on windows i create a docker-compose.yml and i work on it : 

```yaml
version: '3'

services:
  electric_test:
    container_name: electric_test
    image: node:bookworm
    entrypoint: "tail -f /dev/null"
    ports:
      - "3001:3001"
    restart: always
    environment:
      - DEBUG_MODE=true
      - ELECTRIC_URL=your_electric_server
    volumes:
      - ./electric-test:/opt/electric-test
    working_dir: /opt/electric-test
```
