### ISSUE TITLE
Insufficient privileges while connecting to supabase

### ISSUE THREAD

**Issue by masylum** [electric-sql/electric#766]
I'm trying to connect electricsql with postgresql following the guide. I've done all the steps and reviewed several times, and yet, I get the following error (db host masked with XXXX, but it's the correct one):

```
electric-1  | 20:53:38.461 pid=<0.3078.0> origin=postgres_1 [info] connect: %{database: ~c"postgres", host: ~c"db.XXXX.supabase.co", ipv6: false, port: 5432, ssl: false, timeout: 5000, username: ~c"postgres"}
electric-1  | 20:53:40.174 pid=<0.3078.0> origin=postgres_1 [error] ** (CaseClauseError) no case clause matching: {:error, {:error, :error, "42501", :insufficient_privilege, "must be superuser to create subscriptions", [file: "subscriptioncmds.c", line: "545", routine: "CreateSubscription", severity: "ERROR"]}}
electric-1  |     (electric 0.8.1) lib/electric/replication/postgres/client.ex:139: Electric.Replication.Postgres.Client.create_subscription/4
electric-1  |     (electric 0.8.1) lib/electric/replication/postgres_manager.ex:251: Electric.Replication.PostgresConnectorMng.maybe_create_subscription/3
electric-1  |     (electric 0.8.1) lib/electric/replication/postgres_manager.ex:232: anonymous fn/4 in Electric.Replication.PostgresConnectorMng.initialize_postgres/1
electric-1  |     (electric 0.8.1) lib/electric/replication/postgres/client.ex:40: Electric.Replication.Postgres.Client.with_conn/2
electric-1  |     (electric 0.8.1) lib/electric/replication/postgres_manager.ex:96: Electric.Replication.PostgresConnectorMng.handle_continue/2
electric-1  |     (stdlib 4.3.1.2) gen_server.erl:1123: :gen_server.try_dispatch/4
electric-1  |     (stdlib 4.3.1.2) gen_server.erl:1200: :gen_server.handle_msg/6
electric-1  |     (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
electric-1  |
electric-1  | 20:53:40.175 pid=<0.3078.0> origin=postgres_1 [error] Initialization of Postgres state failed with reason: {:error, %CaseClauseError{term: {:error, {:error, :error, "42501", :insufficient_privilege, "must be superuser to create subscriptions", [file: "subscriptioncmds.c", line: "545", routine: "CreateSubscription", severity: "ERROR"]}}}}.
electric-1  | 20:53:40.175 pid=<0.3078.0> origin=postgres_1 [info] schedule retry: 10000
```

I can see that my db has indeed an electric schema, so the connection did work somehow.

This is my docker-compose configuration:

```
  electric:
    image: electricsql/electric:0.8.1
    environment:
      DATABASE_URL: postgresql://${PG_USER}:${PG_PASSWORD}@${PG_HOST}:${PG_PORT}/${PG_DB}
      LOGICAL_PUBLISHER_HOST: electric
      PG_PROXY_PASSWORD: ${PG_PROXY_PASSWORD}
      PG_PROXY_PORT: 65432
      AUTH_JWT_KEY: ${SUPABASE_JWT_SECRET}
      AUTH_JWT_ALG: HS256
      ELECTRIC_INBOUND_MODE: direct_writes
    ports:
      - 5133:5133
      - 65432:65432
    restart: always
```

Any clue how to debug this any further?
